var searchData=
[
  ['package_0',['Running the Testsuite Locally of a Single Package',['../devman_testing.html#pkgTestsuite',1,'']]],
  ['package_20examples_1',['Package Examples',['../tutorials.html#tuto_examples',1,'']]],
  ['package_20manager_2',['Using a Package Manager',['../usage.html#secusingpkgman',1,'']]],
  ['package_20overview_3',['Package Overview',['../packages.html',1,'index']]],
  ['parameterization_4',['Triangulated Surface Mesh Parameterization',['../packages.html#PkgSurfaceMeshParameterization',1,'']]],
  ['partition_5',['Kinetic Space Partition',['../packages.html#PkgKineticSpacePartition',1,'']]],
  ['partitioning_6',['2D Polygon Partitioning',['../packages.html#PkgPartition2',1,'']]],
  ['party_20dependencies_7',['Compilers and Third Party Dependencies',['../thirdparty.html',1,'general_intro']]],
  ['party_20libraries_8',['Party Libraries',['../thirdparty.html#secessential3rdpartysoftware',1,'Essential Third Party Libraries'],['../thirdparty.html#secoptional3rdpartysoftware',1,'Optional Third Party Libraries'],['../configurationvariables.html#installation_variables_third_party',1,'Variables Providing Information About 3rd-Party Libraries']]],
  ['paths_9',['Triangulated Surface Mesh Shortest Paths',['../packages.html#PkgSurfaceMeshShortestPath',1,'']]],
  ['periodic_20hyperbolic_20triangulations_10',['2D Periodic Hyperbolic Triangulations',['../packages.html#PkgPeriodic4HyperbolicTriangulation2',1,'']]],
  ['periodic_20mesh_20generation_11',['3D Periodic Mesh Generation',['../packages.html#PkgPeriodic3Mesh3',1,'']]],
  ['periodic_20triangulations_12',['Periodic Triangulations',['../packages.html#PkgPeriodic2Triangulation2',1,'2D Periodic Triangulations'],['../packages.html#PkgPeriodic3Triangulation3',1,'3D Periodic Triangulations']]],
  ['pipeline_20images_13',['Full Pipeline Images',['../tuto_reconstruction.html#TutorialsReconstruction_pipeline',1,'']]],
  ['pipeline_20overview_14',['Pipeline Overview',['../tuto_reconstruction.html#TutorialsReconstruction_overview',1,'']]],
  ['placement_20of_20streamlines_15',['2D Placement of Streamlines',['../packages.html#PkgStreamLines2',1,'']]],
  ['planar_20convex_20hulls_16',['An example - planar convex hulls',['../devman_traits_classes.html#sectraits_class_example',1,'']]],
  ['point_20clouds_17',['Surface Reconstruction from Point Clouds',['../tuto_reconstruction.html',1,'tutorials']]],
  ['point_20interval_20mpfi_18',['Multiple Precision Floating-point Interval (MPFI)',['../thirdparty.html#thirdpartyMPFI',1,'']]],
  ['point_20reliably_20mpfr_20libraries_19',['GNU Multiple Precision Arithmetic (GMP) and GNU Multiple Precision Floating-Point Reliably (MPFR) Libraries',['../thirdparty.html#thirdpartyMPFR',1,'']]],
  ['point_20sampled_20surfaces_20',['Estimation of Local Differential Properties of Point-Sampled Surfaces',['../packages.html#PkgJetFitting3',1,'']]],
  ['point_20set_21',['3D Point Set',['../packages.html#PkgPointSet3',1,'']]],
  ['point_20set_20processing_22',['Point Set Processing',['../packages.html#PkgPointSetProcessing3',1,'']]],
  ['pointmatcher_23',['PointMatcher',['../thirdparty.html#thirdpartylibpointmatcher',1,'']]],
  ['points_24',['Points',['../packages.html#PkgConvexHull2',1,'2D Convex Hulls and Extreme Points'],['../tutorial_hello_world.html#intro_convex_hull',1,'The Convex Hull of a Sequence of Points']]],
  ['points_20and_20one_20segment_25',['Three Points and One Segment',['../tutorial_hello_world.html#intro_Three',1,'']]],
  ['points_20in_20a_20built_20in_20array_26',['The Convex Hull of Points in a Built-in Array',['../tutorial_hello_world.html#intro_array',1,'']]],
  ['points_20in_20a_20vector_27',['The Convex Hull of Points in a Vector',['../tutorial_hello_world.html#intro_vector',1,'']]],
  ['poisson_28',['Poisson',['../tuto_reconstruction.html#TutorialsReconstruction_reconstruction_poisson',1,'']]],
  ['poisson_20surface_20reconstruction_29',['Poisson Surface Reconstruction',['../packages.html#PkgPoissonSurfaceReconstruction3',1,'']]],
  ['polygon_20mesh_20processing_30',['Polygon Mesh Processing',['../packages.html#PkgPolygonMeshProcessing',1,'']]],
  ['polygon_20offsetting_31',['2D Straight Skeleton and Polygon Offsetting',['../packages.html#PkgStraightSkeleton2',1,'']]],
  ['polygon_20partitioning_32',['2D Polygon Partitioning',['../packages.html#PkgPartition2',1,'']]],
  ['polygon_20repair_33',['2D Polygon Repair',['../packages.html#PkgPolygonRepair',1,'']]],
  ['polygonal_20surface_20reconstruction_34',['Polygonal Surface Reconstruction',['../packages.html#PkgPolygonalSurfaceReconstruction',1,'']]],
  ['polygons_35',['Polygons',['../packages.html#PkgNef2',1,'2D Boolean Operations on Nef Polygons'],['../packages.html#PkgPolygon2',1,'2D Polygons'],['../packages.html#PartPolygons',1,'Polygons']]],
  ['polygons_20embedded_20on_20the_20sphere_36',['2D Boolean Operations on Nef Polygons Embedded on the Sphere',['../packages.html#PkgNefS2',1,'']]],
  ['polyhedra_37',['Polyhedra',['../packages.html#PkgNef3',1,'3D Boolean Operations on Nef Polyhedra'],['../packages.html#PkgMinkowskiSum3',1,'3D Minkowski Sum of Polyhedra'],['../packages.html#PartPolyhedra',1,'Cell Complexes and Polyhedra'],['../packages.html#PkgConvexDecomposition3',1,'Convex Decomposition of Polyhedra']]],
  ['polyhedral_20surface_38',['3D Polyhedral Surface',['../packages.html#PkgPolyhedron',1,'']]],
  ['polyline_20simplification_39',['2D Polyline Simplification',['../packages.html#PkgPolylineSimplification2',1,'']]],
  ['polylines_40',['Splitting Into Polylines',['../tuto_gis.html#TutorialGIS_Contour_Splitting',1,'']]],
  ['polymorphic_20return_20types_41',['Polymorphic Return Types',['../devman_polyret.html',1,'dev_manual']]],
  ['polynomial_42',['Polynomial',['../packages.html#PkgPolynomial',1,'']]],
  ['portability_20issues_43',['Portability Issues',['../devman_portability.html',1,'dev_manual']]],
  ['postconditions_20assertions_20and_20warnings_44',['Checks: Pre- and Postconditions, Assertions, and Warnings',['../devman_checks.html',1,'dev_manual']]],
  ['postprocessing_45',['Output and Postprocessing',['../tuto_reconstruction.html#TutorialsReconstruction_postprocessing',1,'']]],
  ['pre_20and_20postconditions_20assertions_20and_20warnings_46',['Checks: Pre- and Postconditions, Assertions, and Warnings',['../devman_checks.html',1,'dev_manual']]],
  ['precision_20arithmetic_20gmp_20and_20gnu_20multiple_20precision_20floating_20point_20reliably_20mpfr_20libraries_47',['GNU Multiple Precision Arithmetic (GMP) and GNU Multiple Precision Floating-Point Reliably (MPFR) Libraries',['../thirdparty.html#thirdpartyMPFR',1,'']]],
  ['precision_20floating_20point_20interval_20mpfi_48',['Multiple Precision Floating-point Interval (MPFI)',['../thirdparty.html#thirdpartyMPFI',1,'']]],
  ['precompiled_20demo_49',['Trying CGAL algorithms using a Precompiled Demo',['../windows.html#sec-win-demo',1,'']]],
  ['predicates_50',['Number-type based predicates',['../devman_kernels.html#Developer_manualNumber',1,'']]],
  ['predicates_20and_20constructions_51',['The role of predicates and constructions',['../devman_robustness.html#Developer_manualTheroleofpredicatesandconstructions',1,'']]],
  ['preprocessing_52',['Preprocessing',['../tuto_reconstruction.html#TutorialsReconstruction_preprocessing',1,'']]],
  ['prerequisites_53',['Prerequisites',['../usage.html#secprerequisites',1,'']]],
  ['primary_20design_20goals_54',['Primary design goals',['../devman_intro.html#secdesign_goals',1,'']]],
  ['principal_20component_20analysis_55',['Principal Component Analysis',['../packages.html#PkgPrincipalComponentAnalysisD',1,'']]],
  ['problems_20and_20solutions_56',['Various other problems and solutions',['../devman_portability.html#secvarious_problems',1,'']]],
  ['problems_20and_20workarounds_57',['Known problems and workarounds',['../devman_portability.html#secproblems_and_workarounds',1,'']]],
  ['processing_58',['Processing',['../packages.html#PartGeometryProcessing',1,'Geometry Processing'],['../packages.html#PkgPointSetProcessing3',1,'Point Set Processing'],['../packages.html#PkgPolygonMeshProcessing',1,'Polygon Mesh Processing']]],
  ['profiling_20tools_20hash_20map_20union_20find_20modifiers_59',['Profiling tools, Hash Map, Union-find, Modifiers',['../packages.html#Miscellany',1,'']]],
  ['program_60',['Program',['../usage.html#usage_building_program',1,'Building your Program'],['../usage.html#usage_configuring_external',1,'Configuring an External Program'],['../usage.html#usage_configuring',1,'Configuring your Program']]],
  ['program_20using_20cgal_61',['Building a Program using CGAL',['../installation.html#installation_buildprogram',1,'']]],
  ['program_20using_20cgal_62',['Creating a CMake Script for a Program Using CGAL',['../devman_create_cgal_CMakeLists.html',1,'dev_manual']]],
  ['program_20using_20cgal_63',['Quick Start: Compiling a Program using CGAL',['../usage.html#usage_introduction',1,'']]],
  ['programming_20conventions_64',['Programming conventions',['../devman_code_format.html#secprogramming_conventions',1,'']]],
  ['programming_20solver_65',['Linear and Quadratic Programming Solver',['../packages.html#PkgQPSolver',1,'']]],
  ['programs_20such_20as_20demos_20or_20examples_66',['Variables Used Only When Building Programs (Such as Demos or Examples)',['../configurationvariables.html#installation_variables_building',1,'']]],
  ['properties_20of_20point_20sampled_20surfaces_67',['Estimation of Local Differential Properties of Point-Sampled Surfaces',['../packages.html#PkgJetFitting3',1,'']]],
  ['property_20maps_68',['CGAL and Boost Property Maps',['../packages.html#PkgPropertyMap',1,'']]],
  ['propertygraph_69',['PropertyGraph',['../classPropertyGraph.html',1,'']]],
  ['provided_20traits_20classes_70',['CGAL-provided traits classes',['../devman_traits_classes.html#subseccgal_traits_classes',1,'']]],
  ['providing_20information_20about_203rd_20party_20libraries_71',['Variables Providing Information About 3rd-Party Libraries',['../configurationvariables.html#installation_variables_third_party',1,'']]]
];
