var searchData=
[
  ['randomaccesscontainer_0',['RandomAccessContainer',['../classRandomAccessContainer.html',1,'']]],
  ['randomaccessiterator_1',['RandomAccessIterator',['../classRandomAccessIterator.html',1,'']]],
  ['randomaccessrange_2',['RandomAccessRange',['../classRandomAccessRange.html',1,'']]],
  ['range_20and_20neighbor_20search_3',['2D Range and Neighbor Search',['../packages.html#PkgPointSet2',1,'']]],
  ['range_20and_20segment_20trees_4',['dD Range and Segment Trees',['../packages.html#PkgSearchStructures',1,'']]],
  ['rastering_5',['Rastering',['../tuto_gis.html#TutorialGIS_Raster',1,'']]],
  ['rationale_20of_20the_20license_20choice_6',['Rationale of the License Choice',['../license.html#licensesRationale',1,'']]],
  ['readablepropertymap_7',['ReadablePropertyMap',['../classReadablePropertyMap.html',1,'']]],
  ['reading_8',['Reading',['../tutorial_hello_world.html#intro_further',1,'Further Reading'],['../devman_info.html',1,'Recommended Reading']]],
  ['reading_20input_9',['Reading Input',['../tuto_reconstruction.html#TutorialsReconstruction_input',1,'']]],
  ['readwritepropertymap_10',['ReadWritePropertyMap',['../classReadWritePropertyMap.html',1,'']]],
  ['recommendations_11',['Recommendations',['../devman_checks.html#secchecks_req_and_rec',1,'Requirements and recommendations'],['../devman_code_format.html#seccode_format_doc_req_and_rec',1,'Requirements and recommendations'],['../devman_iterators_and_circulators.html#it_and_circit_and_circ_req_and_rec',1,'Requirements and recommendations'],['../devman_memory_management.html#secmemory_req_and_rec',1,'Requirements and recommendations'],['../devman_namespaces.html#Developer_manualRequirementsandrecommendations_1',1,'Requirements and recommendations'],['../devman_portability.html#secportability_req_and_rec',1,'Requirements and recommendations'],['../devman_robustness.html#Developer_manualRequirementsandrecommendations',1,'Requirements and recommendations'],['../devman_traits_classes.html#sectraits_class_req_and_rec',1,'Requirements and recommendations']]],
  ['recommended_20reading_12',['Recommended Reading',['../devman_info.html',1,'dev_manual']]],
  ['reconstruction_13',['Reconstruction',['../packages.html#PkgAdvancingFrontSurfaceReconstruction',1,'Advancing Front Surface Reconstruction'],['../packages.html#PkgKineticSurfaceReconstruction',1,'Kinetic Surface Reconstruction'],['../packages.html#PkgOptimalTransportationReconstruction2',1,'Optimal Transportation Curve Reconstruction'],['../packages.html#PkgPoissonSurfaceReconstruction3',1,'Poisson Surface Reconstruction'],['../packages.html#PkgPolygonalSurfaceReconstruction',1,'Polygonal Surface Reconstruction'],['../tuto_reconstruction.html#TutorialsReconstruction_reconstruction',1,'Reconstruction'],['../packages.html#PkgScaleSpaceReconstruction3',1,'Scale-Space Surface Reconstruction'],['../packages.html#PartReconstruction',1,'Shape Reconstruction']]],
  ['reconstruction_20from_20point_20clouds_14',['Surface Reconstruction from Point Clouds',['../tuto_reconstruction.html',1,'tutorials']]],
  ['reference_20counting_15',['Reference counting',['../devman_reference_counting.html#Developer_manualReferencecounting',1,'']]],
  ['reference_20counting_20and_20handle_20types_16',['Reference Counting and Handle Types',['../devman_reference_counting.html',1,'dev_manual']]],
  ['reference_20manual_17',['Organization of the Reference Manual',['../manual.html#secorganizationref',1,'']]],
  ['references_18',['References',['../tuto_gis.html#TutorialGIS_Reference',1,'']]],
  ['regularization_19',['Shape Regularization',['../packages.html#PkgShapeRegularization',1,'']]],
  ['regularized_20boolean_20set_20operations_20',['2D Regularized Boolean Set-Operations',['../packages.html#PkgBooleanSetOperations2',1,'']]],
  ['release_21',['Debug vs. Release',['../installation.html#installation_debugrelease',1,'']]],
  ['reliably_20mpfr_20libraries_22',['GNU Multiple Precision Arithmetic (GMP) and GNU Multiple Precision Floating-Point Reliably (MPFR) Libraries',['../thirdparty.html#thirdpartyMPFR',1,'']]],
  ['remeshing_23',['Remeshing',['../tuto_gis.html#Tutorial_DTM_hole_filling',1,'Hole Filling and Remeshing'],['../packages.html#PkgTetrahedralRemeshing',1,'Tetrahedral Remeshing']]],
  ['removal_24',['Outlier removal',['../tuto_reconstruction.html#TutorialsReconstruction_preprocessing_outliers',1,'']]],
  ['rep_25',['Rep',['../devman_reference_counting.html#Developer_manualHandleRep',1,'Handle &amp; Rep'],['../devman_reference_counting.html#Developer_manualUsingHandleRep',1,'Using Handle &amp; Rep']]],
  ['repair_26',['2D Polygon Repair',['../packages.html#PkgPolygonRepair',1,'']]],
  ['requirements_27',['Traits class requirements',['../devman_traits_classes.html#subsectraits_class_requirements',1,'']]],
  ['requirements_20and_20recommendations_28',['Requirements and recommendations',['../devman_checks.html#secchecks_req_and_rec',1,'Requirements and recommendations'],['../devman_code_format.html#seccode_format_doc_req_and_rec',1,'Requirements and recommendations'],['../devman_iterators_and_circulators.html#it_and_circit_and_circ_req_and_rec',1,'Requirements and recommendations'],['../devman_memory_management.html#secmemory_req_and_rec',1,'Requirements and recommendations'],['../devman_namespaces.html#Developer_manualRequirementsandrecommendations_1',1,'Requirements and recommendations'],['../devman_portability.html#secportability_req_and_rec',1,'Requirements and recommendations'],['../devman_robustness.html#Developer_manualRequirementsandrecommendations',1,'Requirements and recommendations'],['../devman_traits_classes.html#sectraits_class_req_and_rec',1,'Requirements and recommendations']]],
  ['result_5ftype_29',['result_type',['../classAdaptableUnaryFunction.html#a39168d9ce53b676465388ca54df769e4',1,'AdaptableUnaryFunction::result_type'],['../classAdaptableBinaryFunction.html#aceb8c627b9eda2cfff227ff8e060aa93',1,'AdaptableBinaryFunction::result_type'],['../classAdaptableTernaryFunction.html#a35238b7a2c84a71fa0ae68f41e3481b7',1,'AdaptableTernaryFunction::result_type'],['../classAdaptableQuaternaryFunction.html#a51311fa0132e7f22fb7f0785f66d5efe',1,'AdaptableQuaternaryFunction::result_type'],['../classAdaptableQuinaryFunction.html#a378cb1c805f6bf084bcdb753a1138dd0',1,'AdaptableQuinaryFunction::result_type']]],
  ['return_20types_30',['Polymorphic Return Types',['../devman_polyret.html',1,'dev_manual']]],
  ['reversiblecontainer_31',['ReversibleContainer',['../classReversibleContainer.html',1,'']]],
  ['ridges_20and_20umbilics_20on_20triangulated_20surface_20meshes_32',['Approximation of Ridges and Umbilics on Triangulated Surface Meshes',['../packages.html#PkgRidges3',1,'']]],
  ['robustness_33',['Robustness',['../devman_intro.html#Developer_manualRobustness',1,'']]],
  ['robustness_20issues_34',['Robustness Issues',['../devman_robustness.html',1,'dev_manual']]],
  ['role_20of_20predicates_20and_20constructions_35',['The role of predicates and constructions',['../devman_robustness.html#Developer_manualTheroleofpredicatesandconstructions',1,'']]],
  ['rounding_36',['2D Snap Rounding',['../packages.html#PkgSnapRounding2',1,'']]],
  ['rs_20and_20rs3_37',['RS and RS3',['../thirdparty.html#thirdpartyRS3',1,'']]],
  ['rs_20and_20rs3_20library_38',['RS and RS3 Library',['../configurationvariables.html#installation_rs',1,'']]],
  ['rs3_39',['RS and RS3',['../thirdparty.html#thirdpartyRS3',1,'']]],
  ['rs3_20library_40',['RS and RS3 Library',['../configurationvariables.html#installation_rs',1,'']]],
  ['rules_41',['General rules',['../devman_code_format.html#Developer_manualGeneralrules',1,'']]],
  ['running_20a_20testsuite_20locally_42',['Running a Testsuite Locally',['../devman_testing.html',1,'dev_manual']]],
  ['running_20the_20testsuite_20locally_20of_20a_20single_20package_43',['Running the Testsuite Locally of a Single Package',['../devman_testing.html#pkgTestsuite',1,'']]],
  ['running_20the_20whole_20testsuite_44',['Running the Whole Testsuite',['../devman_testing.html#fullTestsuite',1,'']]]
];
