var searchData=
[
  ['a_20built_20in_20array_0',['The Convex Hull of Points in a Built-in Array',['../tutorial_hello_world.html#intro_array',1,'']]],
  ['a_20cgal_20file_1',['Determining the license of a CGAL file',['../license.html#licensesWhere',1,'']]],
  ['a_20circulator_20for_20your_20container_2',['Writing a circulator for your container',['../devman_iterators_and_circulators.html#secclass_circulator',1,'']]],
  ['a_20cmake_20script_20for_20a_20program_20using_20cgal_3',['Creating a CMake Script for a Program Using CGAL',['../devman_create_cgal_CMakeLists.html',1,'dev_manual']]],
  ['a_20contour_20graph_4',['Building a Contour Graph',['../tuto_gis.html#TutorialGIS_Contour_Extraction',1,'']]],
  ['a_20finer_20granularity_5',['Controlling checks at a finer granularity',['../devman_checks.html#secchecks_controlling',1,'']]],
  ['a_20package_20manager_6',['Using a Package Manager',['../usage.html#secusingpkgman',1,'']]],
  ['a_20precompiled_20demo_7',['Trying CGAL algorithms using a Precompiled Demo',['../windows.html#sec-win-demo',1,'']]],
  ['a_20program_20using_20cgal_8',['A Program using CGAL',['../installation.html#installation_buildprogram',1,'Building a Program using CGAL'],['../usage.html#usage_introduction',1,'Quick Start: Compiling a Program using CGAL']]],
  ['a_20sequence_20of_20points_9',['The Convex Hull of a Sequence of Points',['../tutorial_hello_world.html#intro_convex_hull',1,'']]],
  ['a_20single_20package_10',['Running the Testsuite Locally of a Single Package',['../devman_testing.html#pkgTestsuite',1,'']]],
  ['a_20testsuite_20locally_11',['Running a Testsuite Locally',['../devman_testing.html',1,'dev_manual']]],
  ['a_20vector_12',['The Convex Hull of Points in a Vector',['../tutorial_hello_world.html#intro_vector',1,'']]],
  ['about_203rd_20party_20libraries_13',['Variables Providing Information About 3rd-Party Libraries',['../configurationvariables.html#installation_variables_third_party',1,'']]],
  ['about_20kernels_20and_20traits_20classes_14',['About Kernels and Traits Classes',['../tutorial_hello_world.html#intro_traits',1,'']]],
  ['acknowledging_20cgal_15',['Acknowledging CGAL',['../how_to_cite_cgal.html',1,'']]],
  ['adaptablebinaryfunction_16',['AdaptableBinaryFunction',['../classAdaptableBinaryFunction.html',1,'']]],
  ['adaptablefunctor_17',['AdaptableFunctor',['../classAdaptableFunctor.html',1,'']]],
  ['adaptablequaternaryfunction_18',['AdaptableQuaternaryFunction',['../classAdaptableQuaternaryFunction.html',1,'']]],
  ['adaptablequinaryfunction_19',['AdaptableQuinaryFunction',['../classAdaptableQuinaryFunction.html',1,'']]],
  ['adaptableternaryfunction_20',['AdaptableTernaryFunction',['../classAdaptableTernaryFunction.html',1,'']]],
  ['adaptableunaryfunction_21',['AdaptableUnaryFunction',['../classAdaptableUnaryFunction.html',1,'']]],
  ['adaptor_22',['2D Voronoi Diagram Adaptor',['../packages.html#PkgVoronoiDiagram2',1,'']]],
  ['adding_20function_20objects_20to_20the_20kernel_23',['Adding Function Objects to the Kernel',['../devman_kernels.html#secAddingFunctionObject',1,'']]],
  ['additional_20compiler_20and_20linker_20flags_24',['Additional Compiler and Linker Flags',['../configurationvariables.html#installation_additional_flags',1,'']]],
  ['additional_20dependencies_25',['Additional Dependencies',['../windows.html#sssect-vcpkg-additional-dependencies',1,'Additional Dependencies'],['../windows.html#ssect-installer-additional-dependencies',1,'Additional Dependencies']]],
  ['adjacencygraph_26',['AdjacencyGraph',['../classAdjacencyGraph.html',1,'']]],
  ['adjacencymatrix_27',['AdjacencyMatrix',['../classAdjacencyMatrix.html',1,'']]],
  ['advanced_20configuration_20options_28',['Advanced Configuration Options',['../usage.html#usage_configuring_advanced_cmake',1,'']]],
  ['advanced_20features_29',['Advanced Features',['../manual.html#advanced_features',1,'']]],
  ['advancing_20front_30',['Advancing Front',['../tuto_reconstruction.html#TutorialsReconstruction_reconstruction_advancing',1,'']]],
  ['advancing_20front_20surface_20reconstruction_31',['Advancing Front Surface Reconstruction',['../packages.html#PkgAdvancingFrontSurfaceReconstruction',1,'']]],
  ['algebra_32',['Arithmetic and Algebra',['../packages.html#PartAlgebraicFoundations',1,'']]],
  ['algebraic_20foundations_33',['Algebraic Foundations',['../packages.html#PkgAlgebraicFoundations',1,'']]],
  ['algebraic_20kernel_34',['Algebraic Kernel',['../packages.html#PkgAlgebraicKernelD',1,'']]],
  ['algorithm_20should_20i_20use_35',['Which algorithm should I use?',['../tuto_reconstruction.html#TutorialsReconstruction_algorithms',1,'']]],
  ['algorithms_36',['Algorithms',['../packages.html#PartCombinatorialAlgorithms',1,'Combinatorial Algorithms'],['../packages.html#PartConvexHullAlgorithms',1,'Convex Hull Algorithms'],['../devman_code_format.html#Developer_manualGeometricdatastructuresand',1,'Geometric data structures and algorithms']]],
  ['algorithms_20using_20a_20precompiled_20demo_37',['Trying CGAL algorithms using a Precompiled Demo',['../windows.html#sec-win-demo',1,'']]],
  ['allocation_38',['Allocation',['../devman_reference_counting.html#Developer_manualAllocation',1,'']]],
  ['allocator_39',['Using the allocator',['../devman_memory_management.html#secusing_memory_allocator',1,'']]],
  ['allocator_20macro_40',['The allocator macro',['../devman_memory_management.html#secallocator_macro',1,'']]],
  ['alpha_20shapes_41',['Alpha Shapes',['../packages.html#PkgAlphaShapes2',1,'2D Alpha Shapes'],['../packages.html#PkgAlphaShapes3',1,'3D Alpha Shapes']]],
  ['alpha_20wrapping_42',['3D Alpha Wrapping',['../packages.html#PkgAlphaWrap3',1,'']]],
  ['an_20example_43',['An Example',['../windows.html#sssect-vcpkg-compilation',1,'Compilation of an Example'],['../windows.html#sssect-installer-compilation',1,'Compilation of an Example'],['../windows.html#ssec-vcpkg-compile-example',1,'Compiling an Example'],['../windows.html#ssect-installer-compile-example',1,'Compiling an Example'],['../windows.html#sssec-vcpkg-configuration-example',1,'Configuring of an Example']]],
  ['an_20example_20planar_20convex_20hulls_44',['An example - planar convex hulls',['../devman_traits_classes.html#sectraits_class_example',1,'']]],
  ['an_20example_3a_20traits_20class_20binary_20cross_20checker_45',['An example: Traits class binary cross-checker',['../devman_debugging.html#Developer_manualAnexampleTraitsclassbinary',1,'']]],
  ['an_20external_20program_46',['Configuring an External Program',['../usage.html#usage_configuring_external',1,'']]],
  ['an_20iterator_20for_20your_20container_47',['Writing an iterator for your container',['../devman_iterators_and_circulators.html#secclass_iterator',1,'']]],
  ['analysis_48',['Principal Component Analysis',['../packages.html#PkgPrincipalComponentAnalysisD',1,'']]],
  ['and_203d_20fast_20intersection_20and_20distance_20computation_49',['2D and 3D Fast Intersection and Distance Computation',['../packages.html#PkgAABBTree',1,'']]],
  ['and_203d_20linear_20geometry_20kernel_50',['2D and 3D Linear Geometry Kernel',['../packages.html#PkgKernel23',1,'']]],
  ['and_20algebra_51',['Arithmetic and Algebra',['../packages.html#PartAlgebraicFoundations',1,'']]],
  ['and_20algorithms_52',['Geometric data structures and algorithms',['../devman_code_format.html#Developer_manualGeometricdatastructuresand',1,'']]],
  ['and_20architectures_53',['Identifying compilers and architectures',['../devman_portability.html#secwhich_compiler',1,'']]],
  ['and_20boost_20property_20maps_54',['CGAL and Boost Property Maps',['../packages.html#PkgPropertyMap',1,'']]],
  ['and_20circulator_20traits_55',['Iterator and circulator traits',['../devman_iterators_and_circulators.html#seciterator_traits',1,'']]],
  ['and_20circulators_56',['Handles and Circulators',['../packages.html#PkgHandlesAndCirculators',1,'']]],
  ['and_20circulators_57',['Writing functions for iterators AND circulators',['../devman_iterators_and_circulators.html#secit_and_circ_code',1,'']]],
  ['and_20compiling_20my_20code_20using_20cgal_58',['Configuring and Compiling My Code Using CGAL',['../windows.html#subsect-installer-my-code',1,'']]],
  ['and_20compiling_20your_20code_20using_20cgal_59',['Configuring and Compiling Your Code Using CGAL',['../windows.html#subsect-vpckg-my-code',1,'']]],
  ['and_20configuration_20macros_20and_20flags_60',['Using the version-number and configuration macros and flags',['../devman_portability.html#secusing_version_macros',1,'']]],
  ['and_20constructions_61',['The role of predicates and constructions',['../devman_robustness.html#Developer_manualTheroleofpredicatesandconstructions',1,'']]],
  ['and_20conventions_62',['Kernel design and conventions',['../devman_kernels.html#Developer_manualKerneldesignandconventions',1,'']]],
  ['and_20delaunay_20triangulations_63',['And Delaunay Triangulations',['../packages.html#PkgConvexHullD',1,'dD Convex Hulls and Delaunay Triangulations'],['../packages.html#PartTriangulationsAndDelaunayTriangulations',1,'Triangulations and Delaunay Triangulations']]],
  ['and_20demos_64',['And Demos',['../installation.html#ssec_installation_build_ex_demos',1,'Building Examples and Demos'],['../installation.html#installation_examples',1,'CGAL Examples and Demos']]],
  ['and_20earlier_65',['Version 1.69 and Earlier',['../configurationvariables.html#inst_boost_up_2_1_69',1,'']]],
  ['and_20extreme_20points_66',['2D Convex Hulls and Extreme Points',['../packages.html#PkgConvexHull2',1,'']]],
  ['and_20for_20iterators_20circulators_20and_20handles_67',['Writing code with and for iterators, circulators, and handles',['../devman_iterators_and_circulators.html#Developer_manualWritingcodewithandforiterators',1,'']]],
  ['and_20gnu_20multiple_20precision_20floating_20point_20reliably_20mpfr_20libraries_68',['GNU Multiple Precision Arithmetic (GMP) and GNU Multiple Precision Floating-Point Reliably (MPFR) Libraries',['../thirdparty.html#thirdpartyMPFR',1,'']]],
  ['and_20handle_20types_69',['Reference Counting and Handle Types',['../devman_reference_counting.html',1,'dev_manual']]],
  ['and_20handles_70',['Iterators, Circulators and Handles',['../devman_iterators_and_circulators.html',1,'dev_manual']]],
  ['and_20later_71',['Version 1.72 and Later',['../configurationvariables.html#inst_boost_1_72_plus',1,'']]],
  ['and_20linker_20flags_72',['And Linker Flags',['../configurationvariables.html#installation_additional_flags',1,'Additional Compiler and Linker Flags'],['../configurationvariables.html#installation_flags',1,'Compiler and Linker Flags']]],
  ['and_20meshes_73',['2D Conforming Triangulations and Meshes',['../packages.html#PkgMesh2',1,'']]],
  ['and_20models_74',['Concepts and Models',['../tutorial_hello_world.html#intro_concept',1,'']]],
  ['and_20mpfr_75',['Installing GMP and MPFR',['../windows.html#ssect-installer-gmp-mpfr',1,'']]],
  ['and_20mpfr_20libraries_76',['GMP and MPFR Libraries',['../configurationvariables.html#installation_gmp',1,'']]],
  ['and_20neighbor_20search_77',['2D Range and Neighbor Search',['../packages.html#PkgPointSet2',1,'']]],
  ['and_20one_20segment_78',['Three Points and One Segment',['../tutorial_hello_world.html#intro_Three',1,'']]],
  ['and_20orientation_79',['Normal Estimation and Orientation',['../tuto_reconstruction.html#TutorialsReconstruction_preprocessing_normal',1,'']]],
  ['and_20orthtrees_80',['Quadtrees, Octrees, and Orthtrees',['../packages.html#PkgOrthtree',1,'']]],
  ['and_20output_20iterators_81',['Input and output iterators',['../devman_iterators_and_circulators.html#secinput_and_output_iterators',1,'']]],
  ['and_20polygon_20offsetting_82',['2D Straight Skeleton and Polygon Offsetting',['../packages.html#PkgStraightSkeleton2',1,'']]],
  ['and_20polyhedra_83',['Cell Complexes and Polyhedra',['../packages.html#PartPolyhedra',1,'']]],
  ['and_20postconditions_20assertions_20and_20warnings_84',['Checks: Pre- and Postconditions, Assertions, and Warnings',['../devman_checks.html',1,'dev_manual']]],
  ['and_20postprocessing_85',['Output and Postprocessing',['../tuto_reconstruction.html#TutorialsReconstruction_postprocessing',1,'']]],
  ['and_20quadratic_20programming_20solver_86',['Linear and Quadratic Programming Solver',['../packages.html#PkgQPSolver',1,'']]],
  ['and_20recommendations_87',['And recommendations',['../devman_checks.html#secchecks_req_and_rec',1,'Requirements and recommendations'],['../devman_code_format.html#seccode_format_doc_req_and_rec',1,'Requirements and recommendations'],['../devman_iterators_and_circulators.html#it_and_circit_and_circ_req_and_rec',1,'Requirements and recommendations'],['../devman_memory_management.html#secmemory_req_and_rec',1,'Requirements and recommendations'],['../devman_namespaces.html#Developer_manualRequirementsandrecommendations_1',1,'Requirements and recommendations'],['../devman_portability.html#secportability_req_and_rec',1,'Requirements and recommendations'],['../devman_robustness.html#Developer_manualRequirementsandrecommendations',1,'Requirements and recommendations'],['../devman_traits_classes.html#sectraits_class_req_and_rec',1,'Requirements and recommendations']]],
  ['and_20remeshing_88',['Hole Filling and Remeshing',['../tuto_gis.html#Tutorial_DTM_hole_filling',1,'']]],
  ['and_20rs3_89',['RS and RS3',['../thirdparty.html#thirdpartyRS3',1,'']]],
  ['and_20rs3_20library_90',['RS and RS3 Library',['../configurationvariables.html#installation_rs',1,'']]],
  ['and_20segment_20trees_91',['dD Range and Segment Trees',['../packages.html#PkgSearchStructures',1,'']]],
  ['and_20solutions_92',['Various other problems and solutions',['../devman_portability.html#secvarious_problems',1,'']]],
  ['and_20solvers_93',['CGAL and Solvers',['../packages.html#PkgSolverInterface',1,'']]],
  ['and_20sorted_20matrix_20search_94',['Monotone and Sorted Matrix Search',['../packages.html#PkgMatrixSearch',1,'']]],
  ['and_20sorting_95',['Spatial Searching and Sorting',['../packages.html#PartSearchStructures',1,'']]],
  ['and_20surface_20function_20interpolation_96',['2D and Surface Function Interpolation',['../packages.html#PkgInterpolation2',1,'']]],
  ['and_20the_20boost_20graph_20library_97',['CGAL and the Boost Graph Library',['../packages.html#PkgBGL',1,'']]],
  ['and_20the_20qt_20graphics_20view_20framework_98',['CGAL and the Qt Graphics View Framework',['../packages.html#PkgGraphicsView',1,'']]],
  ['and_20third_20party_20dependencies_99',['Compilers and Third Party Dependencies',['../thirdparty.html',1,'general_intro']]],
  ['and_20traits_20classes_100',['About Kernels and Traits Classes',['../tutorial_hello_world.html#intro_traits',1,'']]],
  ['and_20umbilics_20on_20triangulated_20surface_20meshes_101',['Approximation of Ridges and Umbilics on Triangulated Surface Meshes',['../packages.html#PkgRidges3',1,'']]],
  ['and_20workarounds_102',['Known problems and workarounds',['../devman_portability.html#secproblems_and_workarounds',1,'']]],
  ['apollonius_20graphs_20delaunay_20graphs_20of_20disks_103',['2D Apollonius Graphs (Delaunay Graphs of Disks)',['../packages.html#PkgApolloniusGraph2',1,'']]],
  ['approximation_104',['Triangulated Surface Mesh Approximation',['../packages.html#PkgTSMA',1,'']]],
  ['approximation_20of_20ridges_20and_20umbilics_20on_20triangulated_20surface_20meshes_105',['Approximation of Ridges and Umbilics on Triangulated Surface Meshes',['../packages.html#PkgRidges3',1,'']]],
  ['architectures_106',['Identifying compilers and architectures',['../devman_portability.html#secwhich_compiler',1,'']]],
  ['archive_107',['Archive',['../windows.html#install-from-source',1,'Installing from the Source Archive'],['../usage.html#secusingwebsite',1,'Using CGAL Source Archive']]],
  ['are_20traits_20classes_20in_20cgal_108',['Are traits classes in CGAL',['../devman_traits_classes.html#secwhat_is_a_traits_class',1,'What are traits classes in CGAL?'],['../devman_traits_classes.html#secwhy_traits_classes',1,'Why are traits classes in CGAL?']]],
  ['areas_109',['Inscribed Areas',['../packages.html#PkgInscribedAreas',1,'']]],
  ['argument_5ftype_110',['argument_type',['../classAdaptableUnaryFunction.html#a68c8164d96fc5a826edce4924d7b3f21',1,'AdaptableUnaryFunction']]],
  ['arithmetic_111',['Modular Arithmetic',['../packages.html#PkgModularArithmetic',1,'']]],
  ['arithmetic_20and_20algebra_112',['Arithmetic and Algebra',['../packages.html#PartAlgebraicFoundations',1,'']]],
  ['arithmetic_20gmp_20and_20gnu_20multiple_20precision_20floating_20point_20reliably_20mpfr_20libraries_113',['GNU Multiple Precision Arithmetic (GMP) and GNU Multiple Precision Floating-Point Reliably (MPFR) Libraries',['../thirdparty.html#thirdpartyMPFR',1,'']]],
  ['arrangements_114',['Arrangements',['../packages.html#PkgArrangementOnSurface2',1,'2D Arrangements'],['../packages.html#PartArrangements',1,'Arrangements']]],
  ['array_115',['The Convex Hull of Points in a Built-in Array',['../tutorial_hello_world.html#intro_array',1,'']]],
  ['as_20demos_20or_20examples_116',['Variables Used Only When Building Programs (Such as Demos or Examples)',['../configurationvariables.html#installation_variables_building',1,'']]],
  ['as_20traits_117',['Kernel as traits',['../devman_traits_classes.html#seckernel_traits',1,'']]],
  ['assertions_20and_20warnings_118',['Checks: Pre- and Postconditions, Assertions, and Warnings',['../devman_checks.html',1,'dev_manual']]],
  ['assignable_119',['Assignable',['../classAssignable.html',1,'']]],
  ['associativecontainer_120',['AssociativeContainer',['../classAssociativeContainer.html',1,'']]],
  ['at_20a_20finer_20granularity_121',['Controlling checks at a finer granularity',['../devman_checks.html#secchecks_controlling',1,'']]],
  ['available_20tutorials_122',['List of Available Tutorials',['../tutorials.html#tuto_list',1,'']]]
];
