var searchData=
[
  ['s_20configuration_20variables_0',['Summary of CGAL&apos;s Configuration Variables',['../configurationvariables.html',1,'general_intro']]],
  ['s_20configuration_20variables_1',['Summary of CGAL&apos;s Configuration Variables',['../configurationvariables.html#installation_summary',1,'']]],
  ['safety_2',['Thread Safety',['../preliminaries.html#Preliminaries_thread_safety',1,'']]],
  ['sampled_20surfaces_3',['Estimation of Local Differential Properties of Point-Sampled Surfaces',['../packages.html#PkgJetFitting3',1,'']]],
  ['scale_20space_4',['Scale Space',['../tuto_reconstruction.html#TutorialsReconstruction_reconstruction_scale_space',1,'']]],
  ['scale_20space_20surface_20reconstruction_5',['Scale-Space Surface Reconstruction',['../packages.html#PkgScaleSpaceReconstruction3',1,'']]],
  ['scheme_6',['Naming scheme',['../devman_code_format.html#secnaming_scheme',1,'']]],
  ['scip_7',['SCIP',['../thirdparty.html#thirdpartySCIP',1,'']]],
  ['scip_20library_8',['SCIP library',['../configurationvariables.html#installation_SCIP',1,'']]],
  ['script_20for_20a_20program_20using_20cgal_9',['Creating a CMake Script for a Program Using CGAL',['../devman_create_cgal_CMakeLists.html',1,'dev_manual']]],
  ['search_10',['Search',['../packages.html#PkgPointSet2',1,'2D Range and Neighbor Search'],['../packages.html#PkgMatrixSearch',1,'Monotone and Sorted Matrix Search']]],
  ['searching_11',['dD Spatial Searching',['../packages.html#PkgSpatialSearchingD',1,'']]],
  ['searching_20and_20sorting_12',['Spatial Searching and Sorting',['../packages.html#PartSearchStructures',1,'']]],
  ['second_5fargument_5ftype_13',['second_argument_type',['../classAdaptableBinaryFunction.html#a0960cce03165f227e93eadda482a08b0',1,'AdaptableBinaryFunction::second_argument_type'],['../classAdaptableTernaryFunction.html#a961c79f720297999333fad4a80ed4b71',1,'AdaptableTernaryFunction::second_argument_type'],['../classAdaptableQuaternaryFunction.html#ac836d0777a31004770f096764cc9a48f',1,'AdaptableQuaternaryFunction::second_argument_type'],['../classAdaptableQuinaryFunction.html#a69afa21b3cafa4e7c124fb6a72a46b6d',1,'AdaptableQuinaryFunction::second_argument_type']]],
  ['segment_14',['Three Points and One Segment',['../tutorial_hello_world.html#intro_Three',1,'']]],
  ['segment_20delaunay_20graphs_15',['Segment Delaunay Graphs',['../packages.html#PkgSegmentDelaunayGraph2',1,'2D Segment Delaunay Graphs'],['../packages.html#PkgSegmentDelaunayGraphLinf2',1,'L Infinity Segment Delaunay Graphs']]],
  ['segment_20trees_16',['dD Range and Segment Trees',['../packages.html#PkgSearchStructures',1,'']]],
  ['segmentation_17',['Triangulated Surface Mesh Segmentation',['../packages.html#PkgSurfaceMeshSegmentation',1,'']]],
  ['selection_18',['Component Selection',['../configurationvariables.html#installation_component_selection',1,'']]],
  ['separability_20of_20sets_19',['2D Movable Separability of Sets',['../packages.html#PkgSetMovableSeparability2',1,'']]],
  ['sequence_20of_20points_20',['The Convex Hull of a Sequence of Points',['../tutorial_hello_world.html#intro_convex_hull',1,'']]],
  ['sequencecontainer_21',['SequenceContainer',['../classSequenceContainer.html',1,'']]],
  ['sequences_20of_20dd_20iso_20oriented_20boxes_22',['Intersecting Sequences of dD Iso-oriented Boxes',['../packages.html#PkgBoxIntersectionD',1,'']]],
  ['set_23',['3D Point Set',['../packages.html#PkgPointSet3',1,'']]],
  ['set_20operations_24',['2D Regularized Boolean Set-Operations',['../packages.html#PkgBooleanSetOperations2',1,'']]],
  ['set_20processing_25',['Point Set Processing',['../packages.html#PkgPointSetProcessing3',1,'']]],
  ['sets_26',['2D Movable Separability of Sets',['../packages.html#PkgSetMovableSeparability2',1,'']]],
  ['shape_20detection_27',['Shape Detection',['../packages.html#PkgShapeDetection',1,'']]],
  ['shape_20reconstruction_28',['Shape Reconstruction',['../packages.html#PartReconstruction',1,'']]],
  ['shape_20regularization_29',['Shape Regularization',['../packages.html#PkgShapeRegularization',1,'']]],
  ['shapes_30',['Shapes',['../packages.html#PkgAlphaShapes2',1,'2D Alpha Shapes'],['../packages.html#PkgAlphaShapes3',1,'3D Alpha Shapes']]],
  ['shortest_20paths_31',['Triangulated Surface Mesh Shortest Paths',['../packages.html#PkgSurfaceMeshShortestPath',1,'']]],
  ['should_20i_20use_32',['Which algorithm should I use?',['../tuto_reconstruction.html#TutorialsReconstruction_algorithms',1,'']]],
  ['simplicial_20mesh_20data_20structure_33',['3D Simplicial Mesh Data Structure',['../packages.html#PkgSMDS3',1,'']]],
  ['simplification_34',['Simplification',['../packages.html#PkgPolylineSimplification2',1,'2D Polyline Simplification'],['../tuto_reconstruction.html#TutorialsReconstruction_preprocessing_simplification',1,'Simplification'],['../packages.html#PkgSurfaceMeshSimplification',1,'Triangulated Surface Mesh Simplification']]],
  ['simplifying_35',['Simplifying',['../tuto_gis.html#TutorialGIS_Contour_Simplifying',1,'']]],
  ['single_20package_36',['Running the Testsuite Locally of a Single Package',['../devman_testing.html#pkgTestsuite',1,'']]],
  ['singlepassrange_37',['SinglePassRange',['../classSinglePassRange.html',1,'']]],
  ['skeleton_20and_20polygon_20offsetting_38',['2D Straight Skeleton and Polygon Offsetting',['../packages.html#PkgStraightSkeleton2',1,'']]],
  ['skeletonization_39',['Triangulated Surface Mesh Skeletonization',['../packages.html#PkgSurfaceMeshSkeletonization',1,'']]],
  ['skin_20surface_20meshing_40',['3D Skin Surface Meshing',['../packages.html#PkgSkinSurface3',1,'']]],
  ['skip_20list_41',['Interval Skip List',['../packages.html#PkgIntervalSkipList',1,'']]],
  ['smoothing_42',['Smoothing',['../tuto_reconstruction.html#TutorialsReconstruction_preprocessing_smoothing',1,'']]],
  ['snap_20rounding_43',['2D Snap Rounding',['../packages.html#PkgSnapRounding2',1,'']]],
  ['solutions_44',['Various other problems and solutions',['../devman_portability.html#secvarious_problems',1,'']]],
  ['solver_45',['Solver',['../thirdparty.html#thirdpartyCeres',1,'Ceres Solver'],['../packages.html#PkgQPSolver',1,'Linear and Quadratic Programming Solver']]],
  ['solvers_46',['CGAL and Solvers',['../packages.html#PkgSolverInterface',1,'']]],
  ['sorted_20matrix_20search_47',['Monotone and Sorted Matrix Search',['../packages.html#PkgMatrixSearch',1,'']]],
  ['sorting_48',['Sorting',['../packages.html#PartSearchStructures',1,'Spatial Searching and Sorting'],['../packages.html#PkgSpatialSorting',1,'Spatial Sorting']]],
  ['source_20archive_49',['Source Archive',['../windows.html#install-from-source',1,'Installing from the Source Archive'],['../usage.html#secusingwebsite',1,'Using CGAL Source Archive']]],
  ['space_50',['Scale Space',['../tuto_reconstruction.html#TutorialsReconstruction_reconstruction_scale_space',1,'']]],
  ['space_20partition_51',['Kinetic Space Partition',['../packages.html#PkgKineticSpacePartition',1,'']]],
  ['space_20surface_20reconstruction_52',['Scale-Space Surface Reconstruction',['../packages.html#PkgScaleSpaceReconstruction3',1,'']]],
  ['spanners_53',['Cone-Based Spanners',['../packages.html#PkgConeSpanners2',1,'']]],
  ['spatial_20searching_54',['dD Spatial Searching',['../packages.html#PkgSpatialSearchingD',1,'']]],
  ['spatial_20searching_20and_20sorting_55',['Spatial Searching and Sorting',['../packages.html#PartSearchStructures',1,'']]],
  ['spatial_20sorting_56',['Spatial Sorting',['../packages.html#PkgSpatialSorting',1,'']]],
  ['special_20functionality_57',['Marking of Special Functionality',['../manual.html#markingSpecialFunctionality',1,'']]],
  ['specifying_20missing_20dependencies_58',['Specifying Missing Dependencies',['../usage.html#usage_configuring_cmake_gui',1,'']]],
  ['sphere_59',['Sphere',['../packages.html#PkgNefS2',1,'2D Boolean Operations on Nef Polygons Embedded on the Sphere'],['../packages.html#PkgTriangulationOnSphere2',1,'2D Triangulations on the Sphere']]],
  ['spherical_20geometry_20kernel_60',['3D Spherical Geometry Kernel',['../packages.html#PkgCircularKernel3',1,'']]],
  ['splitting_20into_20polylines_61',['Splitting Into Polylines',['../tuto_gis.html#TutorialGIS_Contour_Splitting',1,'']]],
  ['standard_20template_20library_20stl_62',['Standard Template Library (STL)',['../thirdparty.html#thirdpartystl',1,'']]],
  ['start_3a_20compiling_20a_20program_20using_20cgal_63',['Quick Start: Compiling a Program using CGAL',['../usage.html#usage_introduction',1,'']]],
  ['started_20with_20cgal_64',['Getting Started with CGAL',['../general_intro.html',1,'index']]],
  ['stl_65',['Standard Template Library (STL)',['../thirdparty.html#thirdpartystl',1,'']]],
  ['stl_20extensions_20for_20cgal_66',['STL Extensions for CGAL',['../packages.html#PkgSTLExtension',1,'']]],
  ['storage_67',['Thread Local Storage',['../devman_multithreading.html#Developer_manualThreadlocal',1,'']]],
  ['straight_20skeleton_20and_20polygon_20offsetting_68',['2D Straight Skeleton and Polygon Offsetting',['../packages.html#PkgStraightSkeleton2',1,'']]],
  ['streamlines_69',['2D Placement of Streamlines',['../packages.html#PkgStreamLines2',1,'']]],
  ['streams_70',['I/O Streams',['../packages.html#PkgStreamSupport',1,'']]],
  ['structure_71',['Structure',['../packages.html#PkgTDS2',1,'2D Triangulation Data Structure'],['../packages.html#PkgSMDS3',1,'3D Simplicial Mesh Data Structure'],['../packages.html#PkgTDS3',1,'3D Triangulation Data Structure']]],
  ['structures_72',['Halfedge Data Structures',['../packages.html#PkgHalfedgeDS',1,'']]],
  ['structures_20and_20algorithms_73',['Geometric data structures and algorithms',['../devman_code_format.html#Developer_manualGeometricdatastructuresand',1,'']]],
  ['subdivision_20methods_74',['3D Surface Subdivision Methods',['../packages.html#PkgSurfaceSubdivisionMethod3',1,'']]],
  ['such_20as_20demos_20or_20examples_75',['Variables Used Only When Building Programs (Such as Demos or Examples)',['../configurationvariables.html#installation_variables_building',1,'']]],
  ['sum_20of_20polyhedra_76',['3D Minkowski Sum of Polyhedra',['../packages.html#PkgMinkowskiSum3',1,'']]],
  ['summary_20of_20cgal_20s_20configuration_20variables_77',['Summary of CGAL s Configuration Variables',['../configurationvariables.html',1,'Summary of CGAL&apos;s Configuration Variables'],['../configurationvariables.html#installation_summary',1,'Summary of CGAL&apos;s Configuration Variables']]],
  ['sums_78',['2D Minkowski Sums',['../packages.html#PkgMinkowskiSum2',1,'']]],
  ['support_79',['Support',['../preliminaries.html#Preliminaries_cc0x',1,'C++17 Support'],['../devman_portability.html#secleda_gmp_support',1,'Checking for LEDA or GMP support']]],
  ['support_20features_80',['Debugging Support Features',['../manual.html#debugging_support',1,'']]],
  ['support_20library_81',['Support Library',['../packages.html#PartSupportLibrary',1,'']]],
  ['supported_20compilers_82',['Supported Compilers',['../thirdparty.html#seccompilers',1,'']]],
  ['suppress_20warnings_20using_20cgal_5fassume_83',['Suppress warnings using CGAL_assume.',['../devman_checks.html#secchecks_cgal_assume',1,'']]],
  ['surface_84',['3D Polyhedral Surface',['../packages.html#PkgPolyhedron',1,'']]],
  ['surface_20function_20interpolation_85',['2D and Surface Function Interpolation',['../packages.html#PkgInterpolation2',1,'']]],
  ['surface_20mesh_86',['Surface Mesh',['../packages.html#PkgSurfaceMesh',1,'']]],
  ['surface_20mesh_20approximation_87',['Triangulated Surface Mesh Approximation',['../packages.html#PkgTSMA',1,'']]],
  ['surface_20mesh_20deformation_88',['Triangulated Surface Mesh Deformation',['../packages.html#PkgSurfaceMeshDeformation',1,'']]],
  ['surface_20mesh_20generation_89',['3D Surface Mesh Generation',['../packages.html#PkgSurfaceMesher3',1,'']]],
  ['surface_20mesh_20parameterization_90',['Triangulated Surface Mesh Parameterization',['../packages.html#PkgSurfaceMeshParameterization',1,'']]],
  ['surface_20mesh_20segmentation_91',['Triangulated Surface Mesh Segmentation',['../packages.html#PkgSurfaceMeshSegmentation',1,'']]],
  ['surface_20mesh_20shortest_20paths_92',['Triangulated Surface Mesh Shortest Paths',['../packages.html#PkgSurfaceMeshShortestPath',1,'']]],
  ['surface_20mesh_20simplification_93',['Triangulated Surface Mesh Simplification',['../packages.html#PkgSurfaceMeshSimplification',1,'']]],
  ['surface_20mesh_20skeletonization_94',['Triangulated Surface Mesh Skeletonization',['../packages.html#PkgSurfaceMeshSkeletonization',1,'']]],
  ['surface_20mesh_20topology_95',['Surface Mesh Topology',['../packages.html#PkgSurfaceMeshTopology',1,'']]],
  ['surface_20meshes_96',['Approximation of Ridges and Umbilics on Triangulated Surface Meshes',['../packages.html#PkgRidges3',1,'']]],
  ['surface_20meshing_97',['3D Skin Surface Meshing',['../packages.html#PkgSkinSurface3',1,'']]],
  ['surface_20model_20dsm_98',['Digital Surface Model (DSM)',['../tuto_gis.html#TutorialGIS_DSM',1,'']]],
  ['surface_20reconstruction_99',['Surface Reconstruction',['../packages.html#PkgAdvancingFrontSurfaceReconstruction',1,'Advancing Front Surface Reconstruction'],['../packages.html#PkgKineticSurfaceReconstruction',1,'Kinetic Surface Reconstruction'],['../packages.html#PkgPoissonSurfaceReconstruction3',1,'Poisson Surface Reconstruction'],['../packages.html#PkgPolygonalSurfaceReconstruction',1,'Polygonal Surface Reconstruction'],['../packages.html#PkgScaleSpaceReconstruction3',1,'Scale-Space Surface Reconstruction']]],
  ['surface_20reconstruction_20from_20point_20clouds_100',['Surface Reconstruction from Point Clouds',['../tuto_reconstruction.html',1,'tutorials']]],
  ['surface_20subdivision_20methods_101',['3D Surface Subdivision Methods',['../packages.html#PkgSurfaceSubdivisionMethod3',1,'']]],
  ['surfaces_102',['Estimation of Local Differential Properties of Point-Sampled Surfaces',['../packages.html#PkgJetFitting3',1,'']]],
  ['swappable_103',['Swappable',['../classSwappable.html',1,'']]],
  ['system_104',['GIS (Geographic Information System)',['../tuto_gis.html',1,'tutorials']]]
];
