var searchData=
[
  ['data_20structure_0',['Data Structure',['../packages.html#PkgTDS2',1,'2D Triangulation Data Structure'],['../packages.html#PkgSMDS3',1,'3D Simplicial Mesh Data Structure'],['../packages.html#PkgTDS3',1,'3D Triangulation Data Structure']]],
  ['data_20structures_1',['Halfedge Data Structures',['../packages.html#PkgHalfedgeDS',1,'']]],
  ['data_20structures_20and_20algorithms_2',['Geometric data structures and algorithms',['../devman_code_format.html#Developer_manualGeometricdatastructuresand',1,'']]],
  ['data_5ffile_5fpath_3',['data_file_path',['../namespaceCGAL.html#acdae9a147ad2a3998cc21f88bc292dac',1,'CGAL']]],
  ['dd_20convex_20hulls_20and_20delaunay_20triangulations_4',['dD Convex Hulls and Delaunay Triangulations',['../packages.html#PkgConvexHullD',1,'']]],
  ['dd_20geometry_20kernel_5',['dD Geometry Kernel',['../packages.html#PkgKernelD',1,'']]],
  ['dd_20iso_20oriented_20boxes_6',['Intersecting Sequences of dD Iso-oriented Boxes',['../packages.html#PkgBoxIntersectionD',1,'']]],
  ['dd_20range_20and_20segment_20trees_7',['dD Range and Segment Trees',['../packages.html#PkgSearchStructures',1,'']]],
  ['dd_20spatial_20searching_8',['dD Spatial Searching',['../packages.html#PkgSpatialSearchingD',1,'']]],
  ['dd_20triangulations_9',['dD Triangulations',['../packages.html#PkgTriangulations',1,'']]],
  ['debug_20vs_20release_10',['Debug vs. Release',['../installation.html#installation_debugrelease',1,'']]],
  ['debugging_11',['Graphical debugging',['../devman_debugging.html#secgraphical_debugging',1,'']]],
  ['debugging_20support_20features_12',['Debugging Support Features',['../manual.html#debugging_support',1,'']]],
  ['debugging_20tips_13',['Debugging Tips',['../devman_debugging.html',1,'dev_manual']]],
  ['decomposition_20of_20polyhedra_14',['Convex Decomposition of Polyhedra',['../packages.html#PkgConvexDecomposition3',1,'']]],
  ['defaultconstructible_15',['DefaultConstructible',['../classDefaultConstructible.html',1,'']]],
  ['deformation_16',['Triangulated Surface Mesh Deformation',['../packages.html#PkgSurfaceMeshDeformation',1,'']]],
  ['delaunay_20graphs_17',['Delaunay Graphs',['../packages.html#PkgSegmentDelaunayGraph2',1,'2D Segment Delaunay Graphs'],['../packages.html#PkgSegmentDelaunayGraphLinf2',1,'L Infinity Segment Delaunay Graphs']]],
  ['delaunay_20graphs_20of_20disks_18',['2D Apollonius Graphs (Delaunay Graphs of Disks)',['../packages.html#PkgApolloniusGraph2',1,'']]],
  ['delaunay_20triangulations_19',['Delaunay Triangulations',['../packages.html#PkgHyperbolicTriangulation2',1,'2D Hyperbolic Delaunay Triangulations'],['../packages.html#PkgConvexHullD',1,'dD Convex Hulls and Delaunay Triangulations'],['../packages.html#PartTriangulationsAndDelaunayTriangulations',1,'Triangulations and Delaunay Triangulations']]],
  ['demo_20',['Trying CGAL algorithms using a Precompiled Demo',['../windows.html#sec-win-demo',1,'']]],
  ['demos_21',['Demos',['../installation.html#ssec_installation_build_ex_demos',1,'Building Examples and Demos'],['../installation.html#installation_examples',1,'CGAL Examples and Demos']]],
  ['demos_20or_20examples_22',['Variables Used Only When Building Programs (Such as Demos or Examples)',['../configurationvariables.html#installation_variables_building',1,'']]],
  ['dependencies_23',['Dependencies',['../windows.html#sssect-vcpkg-additional-dependencies',1,'Additional Dependencies'],['../windows.html#ssect-installer-additional-dependencies',1,'Additional Dependencies'],['../thirdparty.html',1,'Compilers and Third Party Dependencies'],['../usage.html#usage_configuring_cmake_gui',1,'Specifying Missing Dependencies']]],
  ['deprecated_20code_24',['Deprecated Code',['../manual.html#deprecated_code',1,'Deprecated Code'],['../deprecated.html#_deprecated000001',1,'Deprecated Code']]],
  ['deprecation_20notice_25',['Deprecation Notice',['../deprecated.html',1,'dev_manual']]],
  ['design_26',['The overall design',['../devman_intro.html#secoverall_design',1,'']]],
  ['design_20and_20conventions_27',['Kernel design and conventions',['../devman_kernels.html#Developer_manualKerneldesignandconventions',1,'']]],
  ['design_20goals_28',['Primary design goals',['../devman_intro.html#secdesign_goals',1,'']]],
  ['detection_29',['Shape Detection',['../packages.html#PkgShapeDetection',1,'']]],
  ['determining_20the_20license_20of_20a_20cgal_20file_30',['Determining the license of a CGAL file',['../license.html#licensesWhere',1,'']]],
  ['developer_20manual_31',['Developer Manual',['../dev_manual.html',1,'index']]],
  ['diagram_20adaptor_32',['2D Voronoi Diagram Adaptor',['../packages.html#PkgVoronoiDiagram2',1,'']]],
  ['diagrams_33',['Voronoi Diagrams',['../packages.html#PartVoronoiDiagrams',1,'']]],
  ['different_20kernels_34',['Different kernels',['../devman_kernels.html#secdifferent_kernels',1,'']]],
  ['differential_20properties_20of_20point_20sampled_20surfaces_35',['Estimation of Local Differential Properties of Point-Sampled Surfaces',['../packages.html#PkgJetFitting3',1,'']]],
  ['digital_20surface_20model_20dsm_36',['Digital Surface Model (DSM)',['../tuto_gis.html#TutorialGIS_DSM',1,'']]],
  ['digital_20terrain_20model_20dtm_37',['Digital Terrain Model (DTM)',['../tuto_gis.html#TutorialGIS_DTM',1,'']]],
  ['disks_38',['2D Apollonius Graphs (Delaunay Graphs of Disks)',['../packages.html#PkgApolloniusGraph2',1,'']]],
  ['distance_20computation_39',['2D and 3D Fast Intersection and Distance Computation',['../packages.html#PkgAABBTree',1,'']]],
  ['distances_40',['Optimal Distances',['../packages.html#PkgPolytopeDistanceD',1,'']]],
  ['downloading_20cgal_41',['Downloading CGAL',['../usage.html#secgettingcgal',1,'']]],
  ['draw_5fsurface_5fmesh_20cpp_42',['draw_surface_mesh.cpp',['../devman_create_and_use_a_cmakelist.html#subexcpp',1,'']]],
  ['dsm_43',['Digital Surface Model (DSM)',['../tuto_gis.html#TutorialGIS_DSM',1,'']]],
  ['dtm_44',['Digital Terrain Model (DTM)',['../tuto_gis.html#TutorialGIS_DTM',1,'']]]
];
