var searchData=
[
  ['l_20infinity_20segment_20delaunay_20graphs_0',['L Infinity Segment Delaunay Graphs',['../packages.html#PkgSegmentDelaunayGraphLinf2',1,'']]],
  ['laslib_1',['LASlib',['../thirdparty.html#thirdpartyLASlib',1,'']]],
  ['laslib_20library_2',['LASlib library',['../configurationvariables.html#installation_laslib',1,'']]],
  ['later_3',['Version 1.72 and Later',['../configurationvariables.html#inst_boost_1_72_plus',1,'']]],
  ['leda_4',['LEDA',['../thirdparty.html#thirdpartyLeda',1,'']]],
  ['leda_20library_5',['LEDA Library',['../configurationvariables.html#installation_leda',1,'']]],
  ['leda_20or_20gmp_20support_6',['Checking for LEDA or GMP support',['../devman_portability.html#secleda_gmp_support',1,'']]],
  ['lessthancomparable_7',['LessThanComparable',['../classLessThanComparable.html',1,'']]],
  ['lgpl_8',['GNU LGPL',['../license.html#licensesLGPL',1,'']]],
  ['lgpl_20version_9',['LGPL version',['../devman_code_format.html#Developer_manualLGPLversion',1,'']]],
  ['libraries_10',['Libraries',['../configurationvariables.html#installation_boost',1,'Boost Libraries'],['../installation.html#seclibraries',1,'CGAL Libraries'],['../thirdparty.html#secessential3rdpartysoftware',1,'Essential Third Party Libraries'],['../configurationvariables.html#installation_gmp',1,'GMP and MPFR Libraries'],['../thirdparty.html#thirdpartyMPFR',1,'GNU Multiple Precision Arithmetic (GMP) and GNU Multiple Precision Floating-Point Reliably (MPFR) Libraries']]],
  ['libraries_11',['Installing CGAL libraries',['../installation.html',1,'general_intro']]],
  ['libraries_12',['Libraries',['../thirdparty.html#secoptional3rdpartysoftware',1,'Optional Third Party Libraries'],['../configurationvariables.html#installation_variables_third_party',1,'Variables Providing Information About 3rd-Party Libraries']]],
  ['library_13',['Library',['../packages.html#PkgBGL',1,'CGAL and the Boost Graph Library'],['../configurationvariables.html#installation_eigen',1,'Eigen Library'],['../configurationvariables.html#installation_esbtl',1,'ESBTL Library'],['../configurationvariables.html#installation_GLPK',1,'GLPK library'],['../configurationvariables.html#installation_laslib',1,'LASlib library'],['../configurationvariables.html#installation_leda',1,'LEDA Library'],['../configurationvariables.html#installation_metis',1,'METIS Library'],['../configurationvariables.html#installation_mpfi',1,'MPFI Library'],['../configurationvariables.html#installation_ntl',1,'NTL Library'],['../configurationvariables.html#installation_OpenCV',1,'OpenCV library'],['../configurationvariables.html#installation_qt6',1,'Qt6 Library'],['../configurationvariables.html#installation_rs',1,'RS and RS3 Library'],['../configurationvariables.html#installation_SCIP',1,'SCIP library'],['../packages.html#PartSupportLibrary',1,'Support Library'],['../configurationvariables.html#installation_tbb',1,'TBB Library']]],
  ['library_20manager_14',['Installing CGAL with the Vcpkg Library Manager',['../windows.html#sec-installing-with-vcpkg',1,'']]],
  ['library_20stl_15',['Standard Template Library (STL)',['../thirdparty.html#thirdpartystl',1,'']]],
  ['license_16',['License',['../license.html',1,'general_intro']]],
  ['license_20checking_17',['License Checking',['../license.html#licenseCheck',1,'']]],
  ['license_20choice_18',['Rationale of the License Choice',['../license.html#licensesRationale',1,'']]],
  ['license_20of_20a_20cgal_20file_19',['Determining the license of a CGAL file',['../license.html#licensesWhere',1,'']]],
  ['licenses_20',['Commercial Licenses',['../license.html#licensesCommercial',1,'']]],
  ['line_20tool_21',['Configuring CGAL with the cmake Command-Line Tool',['../installation.html#installation_configuring_cmd',1,'']]],
  ['linear_20and_20quadratic_20programming_20solver_22',['Linear and Quadratic Programming Solver',['../packages.html#PkgQPSolver',1,'']]],
  ['linear_20cell_20complex_23',['Linear Cell Complex',['../packages.html#PkgLinearCellComplex',1,'']]],
  ['linear_20geometry_20kernel_24',['2D and 3D Linear Geometry Kernel',['../packages.html#PkgKernel23',1,'']]],
  ['linker_20flags_25',['Linker Flags',['../configurationvariables.html#installation_additional_flags',1,'Additional Compiler and Linker Flags'],['../configurationvariables.html#installation_flags',1,'Compiler and Linker Flags']]],
  ['linking_20with_20cgal_26',['Linking with CGAL',['../devman_create_and_use_a_cmakelist.html#seclink',1,'']]],
  ['linux_20macos_27',['Using CGAL on Unix (Linux, macOS, ...)',['../usage.html',1,'general_intro']]],
  ['list_28',['Interval Skip List',['../packages.html#PkgIntervalSkipList',1,'']]],
  ['list_20of_20available_20tutorials_29',['List of Available Tutorials',['../tutorials.html#tuto_list',1,'']]],
  ['local_20differential_20properties_20of_20point_20sampled_20surfaces_30',['Estimation of Local Differential Properties of Point-Sampled Surfaces',['../packages.html#PkgJetFitting3',1,'']]],
  ['local_20storage_31',['Thread Local Storage',['../devman_multithreading.html#Developer_manualThreadlocal',1,'']]],
  ['locally_32',['Running a Testsuite Locally',['../devman_testing.html',1,'dev_manual']]],
  ['locally_20of_20a_20single_20package_33',['Running the Testsuite Locally of a Single Package',['../devman_testing.html#pkgTestsuite',1,'']]],
  ['lvaluepropertymap_34',['LvaluePropertyMap',['../classLvaluePropertyMap.html',1,'']]]
];
