var searchData=
[
  ['halfedge_20data_20structures_0',['Halfedge Data Structures',['../packages.html#PkgHalfedgeDS',1,'']]],
  ['handle_20iterator_20or_20circulator_1',['Handle, iterator, or circulator?',['../devman_iterators_and_circulators.html#sechandle_vs_it_vs_circ',1,'']]],
  ['handle_20rep_2',['Handle Rep',['../devman_reference_counting.html#Developer_manualHandleRep',1,'Handle &amp; Rep'],['../devman_reference_counting.html#Developer_manualUsingHandleRep',1,'Using Handle &amp; Rep']]],
  ['handle_20types_3',['Reference Counting and Handle Types',['../devman_reference_counting.html',1,'dev_manual']]],
  ['handles_4',['Handles',['../devman_iterators_and_circulators.html',1,'Iterators, Circulators and Handles'],['../devman_reference_counting.html#Developer_manualTemplatedhandles',1,'Templated handles'],['../devman_reference_counting.html#Developer_manualUsingtemplatedhandles',1,'Using templated handles'],['../devman_iterators_and_circulators.html#Developer_manualWritingcodewithandforiterators',1,'Writing code with and for iterators, circulators, and handles']]],
  ['handles_20and_20circulators_5',['Handles and Circulators',['../packages.html#PkgHandlesAndCirculators',1,'']]],
  ['handling_6',['Exception handling',['../devman_checks.html#secexception_handling',1,'']]],
  ['hash_20map_20union_20find_20modifiers_7',['Profiling tools, Hash Map, Union-find, Modifiers',['../packages.html#Miscellany',1,'']]],
  ['header_8',['File header',['../devman_code_format.html#secfile_header',1,'']]],
  ['header_20only_20usage_9',['Header-only Usage',['../usage.html#section_headeronly',1,'']]],
  ['heat_20method_10',['The Heat Method',['../packages.html#PkgHeatMethod',1,'']]],
  ['hello_20world_11',['Hello World',['../tutorial_hello_world.html',1,'tutorials']]],
  ['hole_20filling_20and_20remeshing_12',['Hole Filling and Remeshing',['../tuto_gis.html#Tutorial_DTM_hole_filling',1,'']]],
  ['homogeneous_20computation_13',['Cartesian versus homogeneous   computation',['../devman_kernels.html#secCartesianHomogeneousComputation',1,'']]],
  ['how_20to_20use_20cgal_20with_20cmake_14',['How to use CGAL with CMake',['../devman_create_and_use_a_cmakelist.html',1,'general_intro']]],
  ['hull_20algorithms_15',['Convex Hull Algorithms',['../packages.html#PartConvexHullAlgorithms',1,'']]],
  ['hull_20of_20a_20sequence_20of_20points_16',['The Convex Hull of a Sequence of Points',['../tutorial_hello_world.html#intro_convex_hull',1,'']]],
  ['hull_20of_20points_20in_20a_20built_20in_20array_17',['The Convex Hull of Points in a Built-in Array',['../tutorial_hello_world.html#intro_array',1,'']]],
  ['hull_20of_20points_20in_20a_20vector_18',['The Convex Hull of Points in a Vector',['../tutorial_hello_world.html#intro_vector',1,'']]],
  ['hulls_19',['Hulls',['../packages.html#PkgConvexHull3',1,'3D Convex Hulls'],['../devman_traits_classes.html#sectraits_class_example',1,'An example - planar convex hulls']]],
  ['hulls_20and_20delaunay_20triangulations_20',['dD Convex Hulls and Delaunay Triangulations',['../packages.html#PkgConvexHullD',1,'']]],
  ['hulls_20and_20extreme_20points_21',['2D Convex Hulls and Extreme Points',['../packages.html#PkgConvexHull2',1,'']]],
  ['hyperbolic_20delaunay_20triangulations_22',['2D Hyperbolic Delaunay Triangulations',['../packages.html#PkgHyperbolicTriangulation2',1,'']]],
  ['hyperbolic_20triangulations_23',['2D Periodic Hyperbolic Triangulations',['../packages.html#PkgPeriodic4HyperbolicTriangulation2',1,'']]]
];
